# ============================================================
#  emailer.py — Builds and sends the HTML email digest
# ============================================================

import html
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from config import EMAIL_CONFIG



TOPIC_COLORS = [
    "#2563eb", "#7c3aed", "#059669", "#dc2626",
    "#d97706", "#0891b2", "#be185d", "#65a30d",
]


def build_html(digest_sections: list[dict]) -> str:
    # Only include topics that have at least one story
    sections = [s for s in digest_sections if s.get("stories")]
    today = datetime.now().strftime("%A, %B %d, %Y")

    topic_nav = "\n".join(
        f'<a href="#topic-{i}" style="display:inline-block;margin:4px 6px;padding:5px 14px;'
        f'background:{TOPIC_COLORS[i % len(TOPIC_COLORS)]};color:#fff;border-radius:20px;'
        f'font-size:13px;text-decoration:none;">{html.escape(s["topic"])}</a>'
        for i, s in enumerate(sections)
    )

    sections_html = ""
    for i, section in enumerate(sections):
        color = TOPIC_COLORS[i % len(TOPIC_COLORS)]
        stories_html = ""

        for story in section["stories"]:
            url = story.get("url") or ""
            url_safe = html.escape(url) if url and url != "web search result" else ""
            url_html = (
                f'<a href="{url_safe}" style="color:{color};font-size:12px;">Read more →</a>'
                if url_safe else ""
            )
            stories_html += f"""
                <div style="margin-bottom:20px;padding:16px;background:#f9fafb;border-left:4px solid {color};border-radius:4px;">
                    <div style="font-weight:700;font-size:15px;color:#111827;margin-bottom:6px;">{html.escape(story.get('headline', ''))}</div>
                    <div style="font-size:12px;color:#6b7280;margin-bottom:8px;">📰 {html.escape(story.get('source', ''))}</div>
                    <div style="font-size:14px;color:#374151;line-height:1.6;">{html.escape(story.get('summary', ''))}</div>
                    <div style="margin-top:10px;">{url_html}</div>
                </div>"""

        sections_html += f"""
        <div id="topic-{i}" style="margin-bottom:40px;">
            <h2 style="font-size:18px;font-weight:700;color:#fff;background:{color};
                       padding:10px 16px;border-radius:6px;margin:0 0 16px 0;">
                {html.escape(section['topic'])}
            </h2>
            {stories_html}
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:680px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08);">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%);padding:32px 32px 24px;text-align:center;">
      <div style="font-size:28px;font-weight:800;color:#fff;letter-spacing:-0.5px;">📡 Daily News Digest</div>
      <div style="color:#bfdbfe;margin-top:6px;font-size:14px;">{today}</div>
      <div style="margin-top:16px;">{topic_nav}</div>
    </div>

    <!-- Body -->
    <div style="padding:32px;">
      {sections_html}
    </div>

    <!-- Footer -->
    <div style="background:#f9fafb;border-top:1px solid #e5e7eb;padding:20px 32px;text-align:center;
                font-size:12px;color:#9ca3af;">
      Generated by your News Digest Agent · Powered by Groq + NewsAPI + RSS<br>
      Sources: BBC, Reuters, NYT, TechCrunch, The Verge + web search
    </div>
  </div>
</body>
</html>"""


def send_digest(digest_sections: list[dict]) -> bool:
    # Only send sections that have stories
    sections = [s for s in digest_sections if s.get("stories")]
    if not sections:
        print("  No sections with stories to send.")
        return False

    EMAIL_SENDER   = EMAIL_CONFIG["sender_email"]
    EMAIL_PASSWORD = EMAIL_CONFIG["sender_password"]
    recipients     = EMAIL_CONFIG["recipient_emails"]
    SMTP_HOST      = EMAIL_CONFIG["smtp_host"]
    SMTP_PORT      = EMAIL_CONFIG["smtp_port"]

    if not recipients:
        print("  ❌ No recipients configured (set RECIPIENT_EMAILS or recipient_emails in config)")
        return False
    if not EMAIL_SENDER or not EMAIL_PASSWORD:
        print("  ❌ SMTP credentials not set (SENDER_EMAIL, SENDER_PASSWORD or config)")
        return False

    today = datetime.now().strftime("%b %d, %Y")
    subject = f"📡 Your Daily News Digest — {today}"

    html_body = build_html(sections)
    plain_body = "\n\n".join(
        f"=== {s['topic'].upper()} ===\n" +
        "\n\n".join(
            f"• {st['headline']}\n  {st['summary']}\n  {st.get('url', '')}"
            for st in s["stories"]
        )
        for s in sections
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = EMAIL_SENDER
    msg["To"]     = ", ".join(recipients)
    msg.attach(MIMEText(plain_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, recipients, msg.as_string())
        print(f"  ✅ Digest sent to {len(recipients)} recipient(s)")
        return True
    except Exception as e:
        print(f"  ❌ Email send failed: {e}")
        return False
